<?php

use Illuminate\Database\Seeder;
use App\acuerdotipo;
class acuerdotSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $a=new acuerdotipo;
        $a->Tipo="Admisión de Demanda";
        $a->Descripcion="Artículo 32.- Admitida la demanda";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Contestacion de Demanda";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Requerimeinto (Requisitos de Demanda)";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Desecha";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Incompetencia";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Pruebas y Alegatos";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Termino para Ampliación";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Turnar a Sentencia";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Audiencia de Pruebas y Alegatos";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Cumplimiento de Sentencia";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Sentencia Cumplida";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Otros";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Promoción";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Escritura Pública";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Demanda";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Nombramiento";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Recibo de Nómina";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Resolución";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Boleta de Infracción";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Copia Certificada";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Expediente";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Constancia de Notificación";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Oficio";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Concesión";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Admisión de Incidente";
        $a->Descripcion="";
        $a->nivel=2;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Proyecto";
        $a->Descripcion="";
        $a->nivel=4;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Promoción";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Poder para Pleitos y Cobranzas";
        $a->Descripcion="";
        $a->nivel=1;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Amparo";
        $a->Descripcion="";
        $a->nivel=5;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Acta de Notificación";
        $a->Descripcion="";
        $a->nivel=3;
        $a->save();
        $a=new acuerdotipo;
        $a->Tipo="Constancia de Notificación";
        $a->Descripcion="";
        $a->nivel=3;
        $a->save();

    }
}
