<?php

use Illuminate\Database\Seeder;
use App\User;
use App\Role;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $rol_user=Role::where('nombre','Usuario')->first();
        $rol_admin=Role::where('nombre','Administrador')->first();
        $rol_proyectista=Role::where('nombre','Proyectista')->first();
        $rol_oficialp=Role::where('nombre','Oficial de Partes')->first();
        $rol_secretario=Role::where('nombre','Secretario de Acuerdos')->first();
        $rol_actuario=Role::where('nombre','Actuario')->first();
        $rol_magistrado=Role::where('nombre','Magistrado')->first();
        $rol_institucion=Role::where('nombre','Institución')->first();
        $rol_amparo=Role::where('nombre','Amparos')->first();

        //usuarios del sistema
        $user=new User();
        $user->nombre='Admin';
        $user->a_paterno="andres";
        $user->a_materno=" ";
        $user->email='dreamsroom3@gmail.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/mrsmith.png');
        $user->save();
        $user->roles()->attach($rol_admin);

        $user=new User();
        $user->nombre='Gabriela';
        $user->a_paterno="Oficial ";
        $user->a_materno=" de Partes";
        $user->email='oficialpartes@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/fem-avatar.png');
        $user->save();
        $user->roles()->attach($rol_oficialp);

        $user=new User();
        $user->nombre='Secretario Acuerdos ';
        $user->a_paterno="N°";
        $user->a_materno=" 1 ";
        $user->email='sacuerdo1@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/avatar.png');
        $user->save();
        $user->roles()->attach($rol_secretario);

        $user=new User();
        $user->nombre='Secretario Acuerdos ';
        $user->a_paterno="N°";
        $user->a_materno=" 2 ";
        $user->email='sacuerdo2@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/fem-avatar.png');
        $user->save();
        $user->roles()->attach($rol_secretario);

        $user=new User();
        $user->nombre='Actuario';
        $user->a_paterno="N°";
        $user->a_materno=" 1 ";
        $user->email='actuaria1@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/fem-avatar.png');
        $user->save();
        $user->roles()->attach($rol_actuario);

        $user=new User();
        $user->nombre='Actuario';
        $user->a_paterno="N°";
        $user->a_materno=" 2 ";
        $user->email='actuaria2@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/fem-avatar.png');
        $user->save();
        $user->roles()->attach($rol_actuario);

        $user=new User();
        $user->nombre='Proyectista';
        $user->a_paterno="N°";
        $user->a_materno=" 1 ";
        $user->email='proyectista@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/fem-avatar.png');
        $user->save();
        $user->roles()->attach($rol_proyectista);

        $user=new User();
        $user->nombre='Proyectista ';
        $user->a_paterno="N°";
        $user->a_materno=" 2 ";
        $user->email='proyectista2@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/avatar.png');
        $user->save();
        $user->roles()->attach($rol_proyectista);

        $user=new User();
        $user->nombre='Amparos';
        $user->a_paterno="N°";
        $user->a_materno=" 1 ";
        $user->email='amparos@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/avatar.png');
        $user->save();
        $user->roles()->attach($rol_amparo);

        $user=new User();
        $user->nombre='Magistrado';
       	$user->a_paterno="Presidente";
        $user->a_materno=" ";
        $user->email='magistrado@sisede.tcacolima.com';
        $user->password=bcrypt('prueba');
        $user->avatar=('/img/basic/avatar.png');
        $user->save();
        $user->roles()->attach($rol_magistrado);

        // // usuarios regulares e instituciones
        // $user=new User();
        // $user->nombre='JOSE';
        // $user->a_paterno="PEREZ";
        // $user->a_materno="CANTU";
        // $user->email='mail72@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='JAVIER';
        // $user->a_paterno="MORENO";
        // $user->a_materno="MENDOZA";
        // $user->email='recartcolima@hotmail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='JOAQUIN';
        // $user->a_paterno="MACHUCA";
        // $user->a_materno="LIVIER";
        // $user->email='mail73@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);        
        // $user=new User();
        // $user->nombre='Usuario';
        // $user->a_paterno="Prueba";
        // $user->a_materno="1";
        // $user->email='mail210@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Eduardo';
        // $user->a_paterno="Camarena";
        // $user->a_materno="";
        // $user->email='mail74@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Francisco';
        // $user->a_paterno="Santana";
        // $user->a_materno="Roldán";
        // $user->email='mail75@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Manuel Antonio';
        // $user->a_paterno="Rodales";
        // $user->a_materno="Torres";
        // $user->email='mail76@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Francisco Javier';
        // $user->a_paterno="Sanchez";
        // $user->a_materno="Soliz";
        // $user->email='mail77@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Ernesto';
        // $user->a_paterno="Marquez";
        // $user->a_materno="Guerrero";
        // $user->email='mail78@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Victor Humberto';
        // $user->a_paterno="Larios";
        // $user->a_materno="Alonso";
        // $user->email='mail79@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Eduardo';
        // $user->a_paterno="Camarena";
        // $user->a_materno="Berra";
        // $user->email='eduardo.camarena@colima.gob.mx';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Vanessa';
        // $user->a_paterno="Hoyos";
        // $user->a_materno="Villaseñor";
        // $user->email='desarrollourbano@colima.gob.mx';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Orlando';
        // $user->a_paterno="Lino";
        // $user->a_materno="Castellanos";
        // $user->email='mail82@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Gabriela';
        // $user->a_paterno="Benvides";
        // $user->a_materno="Cobos";
        // $user->email='mail83@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Juan Manuel';
        // $user->a_paterno="Olivares";
        // $user->a_materno="Fernandez";
        // $user->email='mail80s4@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='José de Jesús';
        // $user->a_paterno="Sanchez";
        // $user->a_materno="Sanchez";
        // $user->email='mail85@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Francisco Javier';
        // $user->a_paterno="Michel";
        // $user->a_materno="Ruiz";
        // $user->email='francisco.michel@colima.gob.mx';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Juan';
        // $user->a_paterno="Sambrano";
        // $user->a_materno="Ibarra";
        // $user->email='mail87@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Pedro Emanuel';
        // $user->a_paterno="Juarez";
        // $user->a_materno="Arredondo";
        // $user->email='mail88@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Paulina';
        // $user->a_paterno="García";
        // $user->a_materno="Juarez";
        // $user->email='mail89@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Rafael';
        // $user->a_paterno="Mendoza";
        // $user->a_materno="Alonso";
        // $user->email='mail90@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Rodrigo';
        // $user->a_paterno="Gaitán";
        // $user->a_materno="Moreno";
        // $user->email='mail91@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='José Guadalupe';
        // $user->a_paterno="García";
        // $user->a_materno="Negrete";
        // $user->email='mail92@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Salvador';
        // $user->a_paterno="Zuñiga";
        // $user->a_materno="Guerrero";
        // $user->email='mail93@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Francisco Javier';
        // $user->a_paterno="Avalos";
        // $user->a_materno="Gutiérrez";
        // $user->email='francisco.avalos@colima.gob.mx';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Yulenny';
        // $user->a_paterno="Cortés";
        // $user->a_materno="León";
        // $user->email='mail94@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Marcos';
        // $user->a_paterno="Ruiz";
        // $user->a_materno="Cervantes";
        // $user->email='mail95@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Daniel';
        // $user->a_paterno="Valdovinos";
        // $user->a_materno="Cerna";
        // $user->email='mail96@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Miguel';
        // $user->a_paterno="Crispin";
        // $user->a_materno="Hernández";
        // $user->email='mail97@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Darío';
        // $user->a_paterno="Velueta";
        // $user->a_materno="Álvarez";
        // $user->email='mail908@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Ricardo Alberto';
        // $user->a_paterno="Durán";
        // $user->a_materno="Aguilar";
        // $user->email='mail99@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Salvador';
        // $user->a_paterno="Heredia";
        // $user->a_materno="Melendez";
        // $user->email='mail00@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Silverio';
        // $user->a_paterno="Medrano";
        // $user->a_materno="Pérez";
        // $user->email='iscjuanmafa@gmail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Joaquin';
        // $user->a_paterno="Salazar";
        // $user->a_materno="Álvarez";
        // $user->email='mail101@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Andres Alberto';
        // $user->a_paterno="Juarez";
        // $user->a_materno="Jiménez";
        // $user->email='mail102@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Joel';
        // $user->a_paterno="Cardenaz";
        // $user->a_materno="Padilla";
        // $user->email='mail103@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Javier';
        // $user->a_paterno="Salazar";
        // $user->a_materno="Davila";
        // $user->email='mail104@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Pedro';
        // $user->a_paterno="Pereira";
        // $user->a_materno="Uribe";
        // $user->email='mail105@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="6";
        // $user->email='mail106@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Juan Marcos';
        // $user->a_paterno="Martinez";
        // $user->a_materno="Garay";
        // $user->email='mail107@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='David';
        // $user->a_paterno="Jauregui";
        // $user->a_materno="Diaz";
        // $user->email='mail108@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Alejandro';
        // $user->a_paterno="Lopez";
        // $user->a_materno="Llerenas";
        // $user->email='mail109@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Juan Francisco';
        // $user->a_paterno="Rodríguez";
        // $user->a_materno="Luna";
        // $user->email='mail110@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Alfonso ';
        // $user->a_paterno="Madrigal";
        // $user->a_materno="Cervantes";
        // $user->email='mail111@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Maria Concepcion';
        // $user->a_paterno="Torres";
        // $user->a_materno="Acevedo";
        // $user->email='mail112@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Eder Paul';
        // $user->a_paterno="Jaramillo";
        // $user->a_materno="Cazares";
        // $user->email='mail113@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Prueba11';
        // $user->a_paterno="Prueba";
        // $user->a_materno="11";
        // $user->email='mail114@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Juan';
        // $user->a_paterno="Decena";
        // $user->a_materno="Molina";
        // $user->email='mail115@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Pablo';
        // $user->a_paterno="Lechuga";
        // $user->a_materno="Juarez";
        // $user->email='mail116@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='José Ignacio';
        // $user->a_paterno="Vaquero";
        // $user->a_materno="Díaz";
        // $user->email='ignacio.vaquero@colima.gob.mx';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="2";
        // $user->email='mail118@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Rafael';
        // $user->a_paterno="Mendoza";
        // $user->a_materno="Godínez";
        // $user->email='mail119@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Francisco Rafael';
        // $user->a_paterno="Quintero";
        // $user->a_materno="Toscano";
        // $user->email='mail120@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Javier';
        // $user->a_paterno="Radillo";
        // $user->a_materno="Mora";
        // $user->email='mail121@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="8";
        // $user->email='mail122@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);$user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="9";
        // $user->email='mail123@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Manuel Antonio';
        // $user->a_paterno="Sandoval";
        // $user->a_materno="Jaramillo";
        // $user->email='mail124@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Ramiro';
        // $user->a_paterno="Pacheco";
        // $user->a_materno="Salazar";
        // $user->email='mail125@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="4";
        // $user->email='mail126@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Salvador';
        // $user->a_paterno="Ochoa";
        // $user->a_materno="Romero";
        // $user->email='mail127@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Pablo';
        // $user->a_paterno="Neruda";
        // $user->a_materno="Ornelas";
        // $user->email='mail128@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Roberto';
        // $user->a_paterno="Marquez";
        // $user->a_materno="Primas";
        // $user->email='mail129@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Silverio';
        // $user->a_paterno="Solis";
        // $user->a_materno="Cernas";
        // $user->email='mail130@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Patricia';
        // $user->a_paterno="Pinedo";
        // $user->a_materno="Fernandez";
        // $user->email='mail131@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='José Luis';
        // $user->a_paterno="Silva";
        // $user->a_materno="Luna";
        // $user->email='mail132@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Antonio';
        // $user->a_paterno="Moreno";
        // $user->a_materno="Perez";
        // $user->email='mail133@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="3";
        // $user->email='mail134@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Miguel';
        // $user->a_paterno="Solis";
        // $user->a_materno="Prado";
        // $user->email='mail135@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Ernesto';
        // $user->a_paterno="Murguia";
        // $user->a_materno="Gómez";
        // $user->email='mail136@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Paulino';
        // $user->a_paterno="Dominguez";
        // $user->a_materno="Ceja";
        // $user->email='mail137@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='José Guadalupe';
        // $user->a_paterno="Sandoval";
        // $user->a_materno="Estrella";
        // $user->email='mail138@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Crispin';
        // $user->a_paterno="Gutiérrez";
        // $user->a_materno="Moreno";
        // $user->email='crispingtz63@gmail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Francisco Manuel';
        // $user->a_paterno="Sanchez";
        // $user->a_materno="Hurtado";
        // $user->email='fmsanchez@col.gob.mx';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="10";
        // $user->email='mail141@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="7";
        // $user->email='mail142@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Fernando';
        // $user->a_paterno="Madrigal";
        // $user->a_materno="Dueñas";
        // $user->email='mail143@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Sergio';
        // $user->a_paterno="Magaña";
        // $user->a_materno="Magaña";
        // $user->email='mail144@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Wilberto';
        // $user->a_paterno="Morales";
        // $user->a_materno="Montes";
        // $user->email='mail145@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Andres';
        // $user->a_paterno="Dario";
        // $user->a_materno="Silva";
        // $user->email='mail146@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Arnoldo';
        // $user->a_paterno="Ochoa";
        // $user->a_materno="González";
        // $user->email='mail147@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Miguel';
        // $user->a_paterno="Becerra";
        // $user->a_materno="Hernández";
        // $user->email='secretariossa@gmail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Carlos Arturo';
        // $user->a_paterno="Noriega";
        // $user->a_materno="Garcia";
        // $user->email='mail149@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Jaime';
        // $user->a_paterno="Flores";
        // $user->a_materno="Merlo";
        // $user->email='despacho.secretario@secolima.gob.mx';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="101";
        // $user->email='mail1101@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Ignacio';
        // $user->a_paterno="Peralta";
        // $user->a_materno="Sanchez";
        // $user->email='mail152@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Guadalupe';
        // $user->a_paterno="Franco";
        // $user->a_materno="Escobar";
        // $user->email='procurador@pgje.col.gob.mx';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // for ($i=0; $i < 30; $i++) { 
        //    $user=new User();
        //     $user->nombre='Prueba';
        //     $user->a_paterno="prueba";
        //     $user->a_materno="2".$i;
        //     $user->email='mail20'.$i.'@mail.com';
        //     $user->password=bcrypt('prueba');
        //     $user->avatar=('/img/basic/avatar.png');
        //     $user->save();
        //     $user->roles()->attach($rol_user);
        // }
        // $user=new User();
        // $user->nombre='Gabriel Ángel';
        // $user->a_paterno="Zepeda";
        // $user->a_materno="Padilla";
        // $user->email='mail1@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Antonio de Jesús';
        // $user->a_paterno="González";
        // $user->a_materno="López";
        // $user->email='mail2@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Luis';
        // $user->a_paterno="Ochoa";
        // $user->a_materno="Sahagún";
        // $user->email='mail3@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Vicente Emanuel';
        // $user->a_paterno="Solano";
        // $user->a_materno="Anguiano";
        // $user->email='mail4@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='María Magdalena';
        // $user->a_paterno="Pérez";
        // $user->a_materno="Cartañeda";
        // $user->email='mail5@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Eduardo';
        // $user->a_paterno="Padilla";
        // $user->a_materno="Gálvez";
        // $user->email='mail6@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Ignacio';
        // $user->a_paterno="Paz";
        // $user->a_materno="Esparza";
        // $user->email='mail7@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Arturo';
        // $user->a_paterno="Peña";
        // $user->a_materno="Delgadillo";
        // $user->email='mail8@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Reyes';
        // $user->a_paterno="Marcial";
        // $user->a_materno="Hernández";
        // $user->email='mail9@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="31";
        // $user->email='mail10@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Vidal';
        // $user->a_paterno="Reyes";
        // $user->a_materno="Villalvazo";
        // $user->email='mail11@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='María Eufamia';
        // $user->a_paterno="Ramos";
        // $user->a_materno="Castellanos";
        // $user->email='mail12@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="32";
        // $user->email='mail14@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Edgar Manuel';
        // $user->a_paterno="Toscano";
        // $user->a_materno="Moreno";
        // $user->email='mail13@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Jesús Amed';
        // $user->a_paterno="Torres";
        // $user->a_materno="Medina";
        // $user->email='mail15@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Andrés';
        // $user->a_paterno="Ramírez";
        // $user->a_materno="Mendoza";
        // $user->email='mail16@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Francisco Javier';
        // $user->a_paterno="Amezcua";
        // $user->a_materno="Rincón";
        // $user->email='mail17@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Arcadio';
        // $user->a_paterno="Andrade";
        // $user->a_materno="Urzúa";
        // $user->email='mail18@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Teresa';
        // $user->a_paterno="Barragán";
        // $user->a_materno="Ornelas";
        // $user->email='mail19@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='HELIODORO';
        // $user->a_paterno="LANGARICA";
        // $user->a_materno="MUÑOS";
        // $user->email='mail154@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_institucion);
        // $user=new User();
        // $user->nombre='Brayan Iván';
        // $user->a_paterno="Arias";
        // $user->a_materno="Larios";
        // $user->email='mail20@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Cielo María';
        // $user->a_paterno="Larios";
        // $user->a_materno="Cortés";
        // $user->email='mail21@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="5";
        // $user->email='mai1l22@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Luis';
        // $user->a_paterno="Gallegos";
        // $user->a_materno="Martínez";
        // $user->email='mail155@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Adrián';
        // $user->a_paterno="Gallegos";
        // $user->a_materno="Torres";
        // $user->email='mail156@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José de Jesús';
        // $user->a_paterno="Morán";
        // $user->a_materno="Martín";
        // $user->email='mail157@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Vanessa';
        // $user->a_paterno="Amador";
        // $user->a_materno="Orozco";
        // $user->email='mail158@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='María Elba';
        // $user->a_paterno="Rodríguez";
        // $user->a_materno="Camarena";
        // $user->email='mail159@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Saúl Alejandro';
        // $user->a_paterno="Jiménez";
        // $user->a_materno="Sánchez";
        // $user->email='mail160@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='María de Lourdes';
        // $user->a_paterno="Sánchez";
        // $user->a_materno="Martínez";
        // $user->email='mail161@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Pedro Dante';
        // $user->a_paterno="Ceballos";
        // $user->a_materno="Hernández";
        // $user->email='mail162@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="33";
        // $user->email='mail163@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Ezrikam Eckhaus';
        // $user->a_paterno="Solís";
        // $user->a_materno="Cámara";
        // $user->email='mail164@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Luis Eduardo';
        // $user->a_paterno="Schulte";
        // $user->a_materno="Orozco";
        // $user->email='mail165@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Leonardo';
        // $user->a_paterno="Torres";
        // $user->a_materno="González";
        // $user->email='mail166@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Enrique';
        // $user->a_paterno="Barajas";
        // $user->a_materno="De la Vega";
        // $user->email='mail167@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Vanessa';
        // $user->a_paterno="Amador";
        // $user->a_materno="Orozco";
        // $user->email='mail168@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Eduardo';
        // $user->a_paterno="Murillo";
        // $user->a_materno="Lugo";
        // $user->email='mail169@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Carlos Hugo';
        // $user->a_paterno="James";
        // $user->a_materno="Ibañez";
        // $user->email='mail170@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Carlos Alberto';
        // $user->a_paterno="Ramírez";
        // $user->a_materno="Barajas";
        // $user->email='mail171@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Hernán Seúl';
        // $user->a_paterno="Estuardo";
        // $user->a_materno="Cisneros";
        // $user->email='mail172@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="34";
        // $user->email='mail173@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Guillermo';
        // $user->a_paterno="Adame";
        // $user->a_materno="Barreto";
        // $user->email='mail174@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Alberto Ramón';
        // $user->a_paterno="López";
        // $user->a_materno="Peralta";
        // $user->email='mail175@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Gustavo Adolfo';
        // $user->a_paterno="García";
        // $user->a_materno="Molina";
        // $user->email='mail176@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Ma. de Jesús';
        // $user->a_paterno="Ramírez";
        // $user->a_materno="Andrade";
        // $user->email='mail177@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="50";
        // $user->email='mail178@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Mauricio';
        // $user->a_paterno="Cervantes";
        // $user->a_materno="Picazo";
        // $user->email='mail1178@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Prueba';
        // $user->a_paterno="Prueba";
        // $user->a_materno="51";
        // $user->email='mail180@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Armando';
        // $user->a_paterno="Vuelvas";
        // $user->a_materno="Alcaraz";
        // $user->email='mail181@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Hugo Fernando';
        // $user->a_paterno="Sosa";
        // $user->a_materno="Ortega";
        // $user->email='mail182@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Antonio';
        // $user->a_paterno="Cortes";
        // $user->a_materno="Chávez";
        // $user->email='mail183@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Francisco';
        // $user->a_paterno="Pinal";
        // $user->a_materno="Ruiz";
        // $user->email='mail184@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Esteban Armin';
        // $user->a_paterno="Torres";
        // $user->a_materno="Cárdenas";
        // $user->email='mail185@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Roberto';
        // $user->a_paterno="Martínez";
        // $user->a_materno="Pacheco";
        // $user->email='mail186@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Mario Arturo';
        // $user->a_paterno="Bravo";
        // $user->a_materno="Pérez";
        // $user->email='mail187@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Luz del Alba Leonor';
        // $user->a_paterno="López";
        // $user->a_materno="Carmona";
        // $user->email='mail188@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Pablo Abraham';
        // $user->a_paterno="Rodríguez";
        // $user->a_materno="Guzmán";
        // $user->email='mail189@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Imelda María';
        // $user->a_paterno="González";
        // $user->a_materno="Llerenas";
        // $user->email='mail190@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Socorro';
        // $user->a_paterno="Venegas";
        // $user->a_materno="Martínez";
        // $user->email='mail191@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Hugo Alejandro';
        // $user->a_paterno="Ruiz";
        // $user->a_materno="Venegas";
        // $user->email='mail192@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Marco Antonio';
        // $user->a_paterno="Suárez";
        // $user->a_materno="Solís";
        // $user->email='mail193@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Jorge Arturo';
        // $user->a_paterno="Martínez";
        // $user->a_materno="Álvarez";
        // $user->email='mail194@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Pablo';
        // $user->a_paterno="Michel";
        // $user->a_materno="Hernández";
        // $user->email='mail195@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Elda Gizel';
        // $user->a_paterno="Zúñiga";
        // $user->a_materno="Cárdenas";
        // $user->email='mail196@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Víctor David';
        // $user->a_paterno="López";
        // $user->a_materno="Vázquez";
        // $user->email='mail197@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Héctor Darío';
        // $user->a_paterno="Ramírez";
        // $user->a_materno="Medina";
        // $user->email='mail198@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Luis Eduardo';
        // $user->a_paterno="Schulte";
        // $user->a_materno="Orozco";
        // $user->email='mail199@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Héctor Manuel';
        // $user->a_paterno="Brambila";
        // $user->a_materno="Cortés";
        // $user->email='mail230@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Carmen';
        // $user->a_paterno="Castillo";
        // $user->a_materno="Velasco";
        // $user->email='mail231@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Emmanuel Martín';
        // $user->a_paterno="Carreño";
        // $user->a_materno="Ruíz";
        // $user->email='mail232@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='José Alejandro';
        // $user->a_paterno="Lozano";
        // $user->a_materno="Viera";
        // $user->email='mail233@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);
        // $user=new User();
        // $user->nombre='Héctor Manuel';
        // $user->a_paterno="Brambila";
        // $user->a_materno="Cortés";
        // $user->email='mail234@mail.com';
        // $user->password=bcrypt('prueba');
        // $user->avatar=('/img/basic/avatar.png');
        // $user->save();
        // $user->roles()->attach($rol_user);

    }
}
